### ISSUE TITLE
Ability to create multiple instance in an anti-/affinity group

### ISSUE THREAD

**Issue by Ivan-Roger** [terraform-provider-openstack/terraform-provider-openstack#1165]
When trying to create multiple compute instances in an anti-affinity group in parallel (via different requests) the OpenStack scheduler does not know how to ensure anti-/affinity constraints. (See linked problem in references).

The solution is either to create servers one after the other, or to use the multi-create API. This API does not seem to available through this provider.

### Terraform Version
```
Terraform v0.14.5
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.36.0
```

### Affected Resource
- openstack_compute_instance_v2

### Expected Behavior
Create N servers in parallel and have them respect the anti-/affinity groups constraints

### Actual Behavior
Since requests are made in parallel instances are sent to computes and sometimes do not respect the specified constraints.

### Steps to Reproduce
```
resource "openstack_compute_servergroup_v2" "antiaffinity_group" {
  name     = "anti-affinity-group"
  policies = ["anti-affinity"]
}

resource "openstack_compute_instance_v2" "vm_dev" {
  count           = var.instance_count
  name            = "serv${count.index}"

  scheduler_hints {
    group = openstack_compute_servergroup_v2.antiaffinity_group.id
  }
}
```
`terraform apply`

### References
- https://docs.openstack.org/nova/latest/admin/troubleshooting/affinity-policy-violated.html
- https://docs.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail#create-multiple-servers
- https://pkg.go.dev/github.com/gophercloud/gophercloud@v0.15.0/openstack/compute/v2/servers#CreateOpts

**Comment by dave2** [comment]
IIRC `count` is implemented in the core, not provider-specific. As such, I don't think the provider has any knowledge of the `count` parallelism going on. It would probably need a new resource type which had `min` and `max` and presented an array back, but wouldn't be the same syntax as `count`.

It looks like a nova scheduler issue to me that should be resolved on the nova side, and it's not the only case nova scheduling does the wrong thing with groups (eg, it doesn't understand how to avoid scheduling all hosts in parallel to the same host that may not be able to take the sum of the resources asked).

**Comment by Ivan-Roger** [comment]
Hello,
I've been trying to create a new resource with those arguments but considering it shares much of the same code with the standard `instance_v2` resource it would require quite a large refactoring to avoid code duplication.
Would this be a acceptable for you ?

**Comment by kayrus** [comment]
@Ivan-Roger is it something that you're looking for? https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_servergroup_v2#rules

**Comment by Ivan-Roger** [comment]
@kayrus I'm not talking about a server group but about servers (instances) in an anti-affinity group.
I did notice this message in the docs but unfortunately until nova-compute is fixed to not perform a "late affinity check" the problem will still occur.

**Comment by sbauza** [comment]
I've just noticed this issue, but I'll reiterate here that we have a late-affinity check in the compute manager that actually checks whether we violate a hard-affinity policy : 
https://github.com/openstack/nova/blob/01ffb6df85ad895bfe94cc46a3be958dbd266a7a/nova/compute/manager.py#L1813-L1913

The only case when this check isn't run is only when [[workarounds]/disable_group_policy_check_upcall ](https://docs.openstack.org/nova/latest/configuration/config.html#workarounds.disable_group_policy_check_upcall) config option is set to **True**

The recommendation for setting this option to True is only when your deployment has isolated the cells from the API (since the compute will access the API DB). Since by default, this option is set to False, most of the existing deployments **don't** have their hard-affinity policies violated since the check is run.

That being said, this issue here is still legit : IIUC (and correct me if I'm wrong) there is a feature gap in Terraform that doesn't allow to specify instance multicreate, which is something we support at the API level.
When looking at [Terraform docs for create attributes](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_instance_v2#argument-reference), I don't see any for multicreate.

API reference for multicreate is : https://docs.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail#create-multiple-servers and it indeed proposes two optional fields _min_count_ and _max_count_ which could be exposed by Terraform.

HTH to clarify the usecase and the actual problem.

**Comment by nikParasyr** [comment]
@sbauza thanks for your input. I wasnt aware of this check, and this is good to know.

> there is a feature gap in Terraform that doesn't allow to specify instance multicreate, which is something we support at the API level

Im aware but supporting this will be hard due to the problems mentioned above (imo)

**Comment by sbauza** [comment]
> Im aware but supporting this will be hard due to the problems mentioned above (imo)

No worries, I just wanted to clarify the exact usecase for that GitHub issue, which isn't due to a Nova bug, but rather about a feature gap.

**Comment by nitrik** [comment]
> > Would this be a acceptable for you ?
> 
> I'm struggling a lot to see how we can support this feature. Same resource seems easier in terms of code but:
> 
> * its a rather "full" and important resource so any change has to be done very well
> * how are we going to store the state? from api docs you only get a "representation" of this first instance, while you create `max_count` instances. So you still need to somehow figure the id's of the extra instances and somehow store them in a state which is designed for one instance
> 
> So same resource doesn't really work well or at all.
> 
> Going with a new resource I still see problems:
> 
> * how are you going to handle updating the instance? Such as adding a new security group? The api doesnt support any mass update. You would have to loop across all the deployed instances
> * state will still be a mess
> 
> Overall, I find it a bit hard to image a "clear" way of supporting this. I might be missing something or an easier way to approach this.

Simple thought, what if an acceptable solution is to expose _min_count_ and _max_count_ through a single parameter, allowing deployers to get the benefits of the multi-create API to address AF policy issues ?
_min_count_ and _max_count_ would of course be sent to Nova with equal values. 
Wouldn't that solve the messy state you think about ?

**Comment by nikParasyr** [comment]
I dont think it would. The api is completely different => https://docs.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail
Even the response just returns a `reservation_id` so we would have to make a lot of changes to support that and in the end, best case scenario we will only be able to store only 1 vm in the state and manage it via terraform

**Comment by sbauza** [comment]
> I dont think it would. The api is completely different => https://docs.openstack.org/api-ref/compute/?expanded=create-multiple-servers-detail Even the response just returns a `reservation_id` so we would have to make a lot of changes to support that and in the end, best case scenario we will only be able to store only 1 vm in the state and manage it via terraform

I apologize but this is a bit incorrect : the response either returns indeed a reservation_id **or** a representation of the first server. 
The difference is whether you provide a `return_reservation_id` parameter but by default, the parameter is False, so when creating multiple instances, the API just returns the first one.

**Comment by kayrus** [comment]
I think we can implement an optional `create_sequentially` mutex lock during the VMs creation. @nikParasyr, any other ideas about the new argument name?

**Comment by kayrus** [comment]
I created a #1754 PR to mitigate this issue. @Ivan-Roger @dave2 @nitrik @sbauza can you test it with the tf snippet below:

````hcl
resource "openstack_compute_servergroup_v2" "server_group" {
  name     = "test_server_group"
  policies = ["anti-affinity"]
}

resource "openstack_compute_instance_v2" "vm_1" {
  name = "terraform-test-vm"

  security_groups = [
    data.openstack_networking_secgroup_v2.default.name,
  ]

  unlock_on_task_state = "spawning"
  scheduler_hints {
    group = openstack_compute_servergroup_v2.server_group.id
  }

  flavor_id = data.openstack_compute_flavor_v2.vm_flavor_1.id
  key_pair  = data.openstack_compute_keypair_v2.keypair.name
  image_id  = data.openstack_images_image_v2.image.id

  network {
    uuid = data.openstack_networking_network_v2.network_1.id
  }
}

resource "openstack_compute_instance_v2" "vm_2" {
  name = "terraform-test-vm-2"

  security_groups = [
    data.openstack_networking_secgroup_v2.default.name,
  ]

  unlock_on_task_state = "spawning"
  scheduler_hints {
    group = openstack_compute_servergroup_v2.server_group.id
  }

  flavor_id = data.openstack_compute_flavor_v2.vm_flavor_1.id
  key_pair  = data.openstack_compute_keypair_v2.keypair.name
  image_id  = data.openstack_images_image_v2.image.id

  network {
    uuid = data.openstack_networking_network_v2.network_1.id
  }
}
```

maybe it makes sense to hardcode the `spawning` task_state and use a server group ID as a lock. And call a new argument `unlock_on_spawning`. Feedback is welcome.
